// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIvyHA0j1syt0qXGCFnLS4PecYu7ooHTs',
    appId: '1:848793449516:web:b3f8825a0b522ab4598d89',
    messagingSenderId: '848793449516',
    projectId: 'chatapp-86e4c',
    authDomain: 'chatapp-86e4c.firebaseapp.com',
    storageBucket: 'chatapp-86e4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6Y6z8bdJ69P2JA9Uoq2w6E7EU0AU03w',
    appId: '1:848793449516:android:eb496507927a4862598d89',
    messagingSenderId: '848793449516',
    projectId: 'chatapp-86e4c',
    storageBucket: 'chatapp-86e4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDcnJLzxf7_AYJcTBsoIu1sTgOhP69_f0',
    appId: '1:848793449516:ios:8d12f855f89fe326598d89',
    messagingSenderId: '848793449516',
    projectId: 'chatapp-86e4c',
    storageBucket: 'chatapp-86e4c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDcnJLzxf7_AYJcTBsoIu1sTgOhP69_f0',
    appId: '1:848793449516:ios:8d12f855f89fe326598d89',
    messagingSenderId: '848793449516',
    projectId: 'chatapp-86e4c',
    storageBucket: 'chatapp-86e4c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIvyHA0j1syt0qXGCFnLS4PecYu7ooHTs',
    appId: '1:848793449516:web:7cd8dfee1602df56598d89',
    messagingSenderId: '848793449516',
    projectId: 'chatapp-86e4c',
    authDomain: 'chatapp-86e4c.firebaseapp.com',
    storageBucket: 'chatapp-86e4c.firebasestorage.app',
  );
}
